# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RemoteOperations' do
  use_frameworks!

  # Pods for RemoteOperations
  pod 'CoatySwift', '~> 2.1.0'

end
