/*! -----------------------------------------------------------------------------
 * <auto-generated>
 *     This code was generated by a tool.
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 * </auto-generated>
 * ------------------------------------------------------------------------------
 * Copyright (c) 2020 Siemens AG. Licensed under the MIT License.
 */

import { AgentInfo } from "@coaty/core";

export const agentInfo: AgentInfo = {
    packageInfo: {
        name: "remote-operations",
        version: "2.0.0",
    },
    buildInfo: {
        buildDate: "2020-04-09T15:28:23+02:00",
        buildMode: "ghpages",
    },
    configInfo: {
        serviceHost: "",
    },
};
