/*! -----------------------------------------------------------------------------
 * <auto-generated>
 *     This code was generated by a tool.
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 * </auto-generated>
 * ------------------------------------------------------------------------------
 * Copyright (c) 2019 Siemens AG. Licensed under the MIT License.
 */

import { AgentInfo } from "coaty/runtime";

export const agentInfo: AgentInfo = {
    packageInfo: {
        name: "remote-operations",
        version: "1.2.0",
    },
    buildInfo: {
        buildDate: "2019-05-15T16:49:22+02:00",
        buildMode: "ghpages",
    },
    configInfo: {
        serviceHost: "",
    },
};
