/*! -----------------------------------------------------------------------------
 * <auto-generated>
 *     This code was generated by a tool.
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 * </auto-generated>
 * ------------------------------------------------------------------------------
 * Copyright (c) 2019 Siemens AG. Licensed under the MIT License.
 */

import { AgentInfo } from "coaty/runtime";

export const agentInfo: AgentInfo = {
    packageInfo: {
        name: "remote-operations",
        version: "1.3.0",
    },
    buildInfo: {
<<<<<<< HEAD
        buildDate: "2019-05-22T16:13:02+02:00",
=======
        buildDate: "2019-05-22T15:59:05+02:00",
>>>>>>> ef46b234e7f4a40c1cb7f053f3b5be7a5bfe654e
        buildMode: "ghpages",
    },
    configInfo: {
        serviceHost: "",
    },
};
