/*! -----------------------------------------------------------------------------
 * <auto-generated>
 *     This code was generated by a tool.
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 * </auto-generated>
 * ------------------------------------------------------------------------------
 * Copyright (c) 2020 Siemens AG. Licensed under the MIT License.
 */

import { AgentInfo } from "@coaty/core";

export const agentInfo: AgentInfo = {
    packageInfo: {
        name: "sensor-things-dashboard",
        version: "2.0.0",
    },
    buildInfo: {
        buildDate: "2020-03-09T18:26:18+01:00",
        buildMode: "development",
    },
    configInfo: {
        serviceHost: "",
    },
};
