# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SourcesAgent' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inherit! :search_paths
  
  pod 'CoatySwift', '~> 2.2.0'
end

target 'NormalStateActorAgent' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inherit! :search_paths
  
  pod 'CoatySwift', '~> 2.2.0'
end

target 'EmergencyStateActorAgent' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inherit! :search_paths
  
  pod 'CoatySwift', '~> 2.2.0'
end
