# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HelloWorld' do
  use_frameworks!

  # Pods for HelloWorld
  pod 'CoatySwift', '~> 2.1.0'

end

target 'HelloWorld Dynamic' do
  use_frameworks!

  # Pods for HelloWorld Dynamic
  pod 'CoatySwift', '~> 2.1.0'

end
